# Netlify configuration for building and deploying the Vite React app
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://dsa-learning-platform.onrender.com"

# Proxy API requests to the backend service
[[redirects]]
  from = "/api/*"
  to = "https://dsa-learning-platform.onrender.com/:splat"
  status = 200
  force = true

# SPA routing fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 